export default function () {
  return [
    //Application state is generated by reducer functions
    // returns an array of books. list of objects
    { title: 'Interaction Design' },
    { title: 'Envisioning Information' },
    { title: 'The Mythical Man-Month' },
    { title: 'The Circle' }
  ]
}
