export default function () {
  return [
    // Application state is generated by reducer functions
    // returns an array of books. list of objects
    { title: 'Interaction Design', author: 'by Jenny Preece and Helen Sharp' },
    { title: 'Envisioning Information', author: 'by Edward R. Tufte' },
    { title: 'The Mythical Man-Month', author: 'by Frederick P. Brooks Jr.' },
    { title: 'The Circle', author: 'Novel by Dave Eggers' }
  ]
}
