export default function () {
  return [
    // Application state is generated by reducer functions
    // returns an array of books. list of objects
    { title: 'Interaction Design',
      author: 'by Jenny Preece and Helen Sharp',
      image: 'style/images/interaction-design.jpg'},

    { title: 'Envisioning Information',
      author: 'by Edward R. Tufte',
      image: '../style/images/envisioning-information.jpg'},

    { title: 'The Mythical Man-Month',
      author: 'by Frederick P. Brooks Jr.',
      image: '../style/images/mythical-man-month.jpg' },

    { title: 'The Circle',
      author: 'Novel by Dave Eggers',
      image: '../style/images/the-circle.jpeg' }
  ]
}
